routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\LeagueController;

Route::get('/', [LeagueController::class, 'index'])->name('home');
Route::get('/simulate-all', [LeagueController::class, 'simulateAllMatches'])->name('simulate-all');
Route::get('/standings', [LeagueController::class, 'displayStandings'])->name('standings');

app/Models/PlayedMatch.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class PlayedMatch extends Model
{
    use HasFactory;

    protected $table = 'played_matches';

    public function home_team() : BelongsTo
    {
        return $this->belongsTo(Team::class,'home_team_id');
    }

    public function away_team() : BelongsTo
    {
        return $this->belongsTo(Team::class,'away_team_id');
    }
}

app/Models/Team.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Team extends Model
{
    use HasFactory;

    protected $table = 'teams';

    protected $fillable = ['played','win','draw','lost','goal_scored','goal_conceded'];

    public function getPointsAttribute() : int
    {
        return ($this->win * 3) + $this->draw;
    }

    public function getGoalDifference() : int
    {
        return $this->goals_scored - $this->goals_conceded;
    }

    public function home_matches() : HasMany
    {
        return $this->hasMany(PlayedMatch::class,'home_team_id');
    }

    public function away_matches() : HasMany
    {
        return $this->hasMany(PlayedMatch::class,'away_team_id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LeagueController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\MatchesRepository;
use App\Repositories\TeamsRepository;
use App\Services\PlayMatchService;
use App\Services\SimulateAllMatchesService;

class LeagueController extends Controller
{
    public function __construct(
        private  TeamsRepository $teamsRepository,
        private  MatchesRepository $matchesRepository,
        private  SimulateAllMatchesService $allMatchesService,
    )
    {
    }

    public function index()
    {
        $teams = $this->teamsRepository->get();

        return view('index', compact('teams'));
    }

    public function simulateAllMatches()
    {
        $this->allMatchesService->simulateAllMatches();


    }

}

resources/views/includes/header.blade.php
<div class="container mb-5">
    <div class="row text-center">
        <!-- As a link -->
        <nav class="navbar navbar-light bg-light text-center">
            <a class="navbar-brand" href="#">League Simulation</a>
        </nav>
    </div>
</div>

resources/views/includes/scripts.blade.php
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
@yield('scripts')

resources/views/includes/styles.blade.php
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
@yield('styles')

resources/views/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>League Table</h3>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Teams</th>
                            <th scope="col">Points</th>
                            <th scope="col">P</th>
                            <th scope="col">W</th>
                            <th scope="col">D</th>
                            <th scope="col">L</th>
                            <th scope="col">GD</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($teams as $team)
                            <tr>
                                <td>{{$team->name}}</td>
                                <td>{{$team->points}}</td>
                                <td>{{$team->played}}</td>
                                <td>{{$team->win}}</td>
                                <td>{{$team->draw}}</td>
                                <td>{{$team->lost}}</td>
                                <td>{{$team->getGoalDifference()}}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <button type="button" id="all_matches" class="btn btn-primary">Play All Matches</button>
                <button type="button" id="week_matches" class="btn btn-success">Play Next Week</button>
            </div>
        </div>
    </div>
@stop

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>League Simulation</title>
    @include('includes.styles')
</head>
<body>
@include('includes.header')
 @yield('content')

@include('includes.scripts')
</body>
</html>

resources/views/standings.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>League Standings</title>
</head>
<body>
<h1>League Standings</h1>
<table>
    <tr>
        <th>Position</th>
        <th>Team</th>
        <th>Points</th>
        <th>Goals Scored</th>
        <th>Goals Conceded</th>
        <th>Goal Difference</th>
    </tr>
    @foreach($teams as $index => $team)
        <tr>
            <td>{{ $index + 1 }}</td>
            <td>{{ $team->name }}</td>
            <td>{{ $team->points }}</td>
            <td>{{ $team->goalsScored }}</td>
            <td>{{ $team->goalsConceded }}</td>
            <td>{{ $team->goalsScored - $team->goalsConceded }}</td>
        </tr>
    @endforeach
</table>
</body>
</html>